package: neues_structure
version: '6.0.0-dev-2025-30-01'
author: 'Alexander Walther für FriendsOfREDAXO'
supportpage: https://github.com/FriendsOfREDAXO/neues_structure


requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.18
    packages:
        yform: "^4"
        neues: ">=6.0.0"

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
