package: neues_structure
version: '6.0.0-dev-2025-28-06'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/neues_structure


requires:
    php:
        version: '>=8.3,<9'
    redaxo: ^5.18
    packages:
        yform: ">=4,<6"
        neues: ">=6.0.0"

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
